name: Publish to NPM

on:
  push:
    branches:
      - performance

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Set environment variables for OpenAI API and NPM
      - name: Set up environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "OPENAI_API_ENDPOINT=${{ secrets.OPENAI_API_ENDPOINT }}" >> $GITHUB_ENV
          
      # Publish to NPM
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}      # NPM Token for authentication
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Your OpenAI API key
          OPENAI_API_ENDPOINT: ${{ secrets.OPENAI_API_ENDPOINT }}  # Your OpenAI API endpoint
        run: npm publish
